if(NOT DEFINED OPENLIST_SORTER_DEPLOY_TARGET)
  message(FATAL_ERROR "OPENLIST_SORTER_DEPLOY_TARGET is required")
endif()

if(NOT DEFINED OPENLIST_SORTER_DEPLOY_DIR)
  message(FATAL_ERROR "OPENLIST_SORTER_DEPLOY_DIR is required")
endif()

set(OPENLIST_SORTER_DEPLOY_SEARCH_DIRS "")
if(DEFINED OPENLIST_SORTER_DEPLOY_QT_ROOT AND NOT OPENLIST_SORTER_DEPLOY_QT_ROOT STREQUAL "")
  if(EXISTS "${OPENLIST_SORTER_DEPLOY_QT_ROOT}/lib")
    list(APPEND OPENLIST_SORTER_DEPLOY_SEARCH_DIRS "${OPENLIST_SORTER_DEPLOY_QT_ROOT}/lib")
  endif()
endif()

set(OPENLIST_SORTER_DEPLOY_EXTRA_ARGS "")
if(OPENLIST_SORTER_DEPLOY_SEARCH_DIRS)
  list(APPEND OPENLIST_SORTER_DEPLOY_EXTRA_ARGS DIRECTORIES ${OPENLIST_SORTER_DEPLOY_SEARCH_DIRS})
endif()

file(MAKE_DIRECTORY "${OPENLIST_SORTER_DEPLOY_DIR}")
file(GET_RUNTIME_DEPENDENCIES
  EXECUTABLES "${OPENLIST_SORTER_DEPLOY_TARGET}"
  RESOLVED_DEPENDENCIES_VAR OPENLIST_SORTER_DEPLOY_RESOLVED_DEPS
  UNRESOLVED_DEPENDENCIES_VAR OPENLIST_SORTER_DEPLOY_UNRESOLVED_DEPS
  PRE_EXCLUDE_REGEXES
    [[^linux-vdso\.so]]
  POST_EXCLUDE_REGEXES
    [[^/lib/]]
    [[^/lib64/]]
    [[^/usr/lib/]]
    [[^/usr/lib64/]]
  ${OPENLIST_SORTER_DEPLOY_EXTRA_ARGS}
)

foreach(runtime_dep IN LISTS OPENLIST_SORTER_DEPLOY_RESOLVED_DEPS)
  file(COPY "${runtime_dep}" DESTINATION "${OPENLIST_SORTER_DEPLOY_DIR}")
endforeach()

if(OPENLIST_SORTER_DEPLOY_UNRESOLVED_DEPS)
  message(WARNING
    "Some runtime dependencies could not be resolved: "
    "${OPENLIST_SORTER_DEPLOY_UNRESOLVED_DEPS}")
endif()

